// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSYOIZGjOMzG77Hfelya7xshnOa7c9Jg',
    appId: '1:196355610623:android:b0c6edbab8bccf20c179ca',
    messagingSenderId: '196355610623',
    projectId: 'scetflutter',
    storageBucket: 'scetflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy29GVA-UQNTr7lGkxs1qUvkK4nET7l80',
    appId: '1:196355610623:ios:4210fce4f9592964c179ca',
    messagingSenderId: '196355610623',
    projectId: 'scetflutter',
    storageBucket: 'scetflutter.firebasestorage.app',
    iosBundleId: 'com.example.heroAnimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy29GVA-UQNTr7lGkxs1qUvkK4nET7l80',
    appId: '1:196355610623:ios:4210fce4f9592964c179ca',
    messagingSenderId: '196355610623',
    projectId: 'scetflutter',
    storageBucket: 'scetflutter.firebasestorage.app',
    iosBundleId: 'com.example.heroAnimation',
  );
}
